# Generated by Django 6.0 on 2026-01-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namep', models.CharField(max_length=100)),
                ('descp', models.TextField(max_length=100)),
                ('pricep', models.IntegerField()),
                ('catp', models.CharField(max_length=100)),
                ('imgp', models.CharField(max_length=100)),
            ],
        ),
    ]
